server:
  port: ${PORT:8080}

spring:
  profiles: local 
eureka:
  instance:
    hostname:  localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---  
spring:
  profiles: heroku
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/	   