server:
  port: ${PORT:8080}

spring:
  profiles: local 
eureka:
  instance:
    hostname:  localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://warm-ocean-4454.herokuapp.com/eureka/

---  
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    leaseRenewalIntervalInSeconds: 10
    nonSecurePort: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/	   