server:
  port: ${PORT:8080}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
	
spring:
  profiles: heroku
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80	
    
    